services:
  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - mongo_data:/data/db

  php:
    build: ./php
    container_name: php_app
    restart: always
    environment:
      MONGO_URI: "mongodb://admin:admin_password@mongodb:27017"
    volumes:
      - ./errors:/var/www/html/errors
      - ./uploads:/var/www/html/uploads
      - ./jobs:/var/www/html/jobs
    depends_on:
      - mongodb

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  mongo_data:
