services:
  mongodb:
    image: mongo:7
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  php:
    build: ./php
    container_name: php_app
    restart: always
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017"
    volumes:
      - ./errors:/var/www/html/errors
      - ./uploads:/var/www/html/uploads
      - ./jobs:/var/www/html/jobs
    depends_on:
      - mongodb
      
  cron:
    build: ./php
    container_name: php_cron
    restart: always
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017"
    volumes:
      - ./errors:/var/www/html/errors
      - ./uploads:/var/www/html/uploads
      - ./jobs:/var/www/html/jobs
    depends_on:
      - mongodb
    command: ["/bin/sh", "-c", "while true; do php /var/www/html/cleanup.php || true; sleep 3600; done"]
    
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  mongo_data:
