version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: zhkh_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: zhkh_layout
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:80"

volumes:
  mongo_data:
